# Generated by Django 6.0.6 on 2026-06-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('creator', 'Creator'), ('super_admin', 'Super_admin')], default='creator', max_length=500, null=True),
        ),
    ]
