# Generated by Django 6.0.6 on 2026-06-21 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_conversation_generation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.conversation'),
        ),
    ]
